name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run tests
        run: go test -cover ./...
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check for Go formatting
        run: test -z $(go fmt ./...)
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ hashFiles('**/go.sum') }}
