name: ci
on:
  pull_request:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run tests
        run: go test -cover ./...
        working-directory: ./learn-cicd-starter
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Check for Go formatting
        run: test -z $(go fmt ./...)
        working-directory: ./learn-cicd-starter
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ runner.os }}-staticcheck
          working-directory: ./learn-cicd-starter
